version: "3.8"
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server
    user: root
  orderdb:
    image: mcr.microsoft.com/mssql/server
    user: root
  rabbitmq:
    image: rabbitmq:3.8.14-management
  catalog.api:
    image: catalog_api_image
    build:
      context: .
      dockerfile: Services/Catalog/FreeCourse.Services.Catalog/Dockerfile
  basket.api:
    image: basket_api_image
    build:
      context: .
      dockerfile: Services/Basket/FreeCourse.Services.Basket/Dockerfile
  photostock.api:
    image: photostock_api_image
    build:
      context: .
      dockerfile: Services/PhotoStock/FreeCourse.Services.PhotoStock/Dockerfile
  identityserver.api:
    image: identityserver_api_image
    build:
      context: .
      dockerfile: IdentityServer/FreeCourse.IdentityServer/Dockerfile
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:
  





